services:
  # product-service:
  #   image: product-service
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/product_service
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=product_service
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
